# Build Spec for AWS CodeBuild CI

version: 0.2
env:
  variables:
    run_pytest_pytorch: "enable"
    run_pytest_mxnet: "enable"
    run_pytest_tensorflow: "enable"
phases:
  install:
    commands:
        -  . config/set_env.sh
        - su && apt-get update
        - apt-get install sudo
        - sudo apt-get update
        - sudo apt-get install unzip
        - cd $CODEBUILD_SRC_DIR  && chmod +x config/protoc_downloader.sh && ./config/protoc_downloader.sh
        - pip install pytest wheel pyYaml pytest-html tensorflow mxnet torch
        - pip uninstall -y boto3 && pip uninstall -y aiobotocore && pip uninstall -y botocore

  pre_build:
    commands:
    
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR  && python setup.py bdist_wheel --universal && pip install dist/*.whl && cd ..
      - cd $CODEBUILD_SRC_DIR  && chmod +x config/tests.sh && ./config/tests.sh  && mkdir -p upload/$CURRENT_COMMIT_PATH/wheels && cp ./dist/*.whl upload/$CURRENT_COMMIT_PATH/wheels && cd ..
#if [ "$CODEBUILD_GIT_BRANCH" = "master" ] && [ "$CODEBUILD_WEBHOOK_EVENT" = "PUSH" ] ; then
  post_build:
    commands:
      - cat $CODEBUILD_SRC_DIR/upload/$CURRENT_COMMIT_PATH/reports/*.html >> $CODEBUILD_SRC_DIR/upload/$CURRENT_COMMIT_PATH/reports/all_tests.html
      - aws s3 cp $CODEBUILD_SRC_DIR/upload s3://tornasolecodebuildtest/ --recursive
      - if [ "$CODEBUILD_BUILD_SUCCEEDING" -eq 0 ]; then echo "ERROR BUILD FAILED , ACCESS BUILD LOGS THROUGH GITHUB OR TROUGH THE LINK PR:$GITHUB_PR_URL , CODEBUILD:$CODEBUILD_CURRENT_BUILD_URL , Test logs are on S3 here:$S3_TEST_REPORT_URL" ; fi
      - if [ "$CODEBUILD_BUILD_SUCCEEDING" -eq 1 ]; then echo "INFO BUILD SUCCEEDED !!! , ACCESS BUILD LOGS THROUGH GITHUB OR TROUGH THE LINK PR:$GITHUB_PR_URL , CODEBUILD:$CODEBUILD_CURRENT_BUILD_URL , Test logs are on S3 here:$S3_TEST_REPORT_URL" ; fi
