# Build Spec for AWS CodeBuild CI

version: 0.2
env:
  variables:
    run_pytest_pytorch: "enable"
    run_pytest_mxnet: "enable"
    run_pytest_tensorflow: "enable"
    run_pytest_xgboost: "enable"
phases:
  install:
    commands:
        -  . config/change_branch.sh
        - su && apt-get update
        - apt-get install sudo
        - sudo apt-get update
        - sudo apt-get install unzip
        - cd $CODEBUILD_SRC_DIR  && chmod +x config/protoc_downloader.sh && ./config/protoc_downloader.sh
        - pip install pytest wheel pyYaml pytest-html tensorflow==1.14.0 mxnet torch xgboost
        - pip uninstall -y boto3 && pip uninstall -y aiobotocore && pip uninstall -y botocore

  pre_build:
    commands:

  build:
    commands:
      - cd $CODEBUILD_SRC_DIR  && python setup.py bdist_wheel --universal && pip install dist/*.whl && cd ..
      - cd $CODEBUILD_SRC_DIR  && chmod +x config/tests.sh && ./config/tests.sh  && mkdir -p upload/$CURRENT_COMMIT_PATH/wheels && cp ./dist/*.whl upload/$CURRENT_COMMIT_PATH/wheels && cd ..
#if [ "$CODEBUILD_GIT_BRANCH" = "master" ] && [ "$CODEBUILD_WEBHOOK_EVENT" = "PUSH" ] ; then
  post_build:
    commands:
      - . $CODEBUILD_SRC_DIR/config/upload_on_end.sh
      - rm -rf $CODEBUILD_SRC_DIR/upload/$CURRENT_COMMIT_PATH
